Feature/increment7
maffka123/metricCollector pull request #9
Opened 2022-01-08 17:53 UTC by maffka123

2022-01-12 11:36 UTC, Bazys requested changes
Небольшие комментарии, времени много на исправление не займет, а до конца спринта время еще есть.

2022-01-12 11:36 UTC, Bazys commented on cmd/agent/main.go
> +var cfg config.Config
Пока эти переменными были по сути константами, не страшно было их держать в глобальной области видимости.
Теперь же лучше убрать из глобальных переменных.

2022-01-12 11:36 UTC, Bazys commented on cmd/agent/main.go
> +	metricList := agent.InitMetrics(&cfg, client)
А какой здесь смысл в передаче по ссылке?

2022-01-12 11:36 UTC, Bazys commented on cmd/agent/main.go
> +	go agent.SendAllData(ctx, &cfg, reportTicker.C, client, metricList)
здесь аналогично

2022-01-12 11:36 UTC, Bazys commented on cmd/agent/main.go
> +func init() {
Не очень хорошая в целом практика использовать init() 
Основная с ней проблема, никто не гарантирует последовательность выполнения.
Проще эти три строчки просто в тело main()

2022-01-12 11:36 UTC, Bazys commented on cmd/server/main.go
> +var cfg config.Config
аналогично как и с агентом.

2022-01-12 11:42 UTC, Bazys commented
Насчет покрыть код агента и сервера тестами.
Да надо писать отдельну функцию, что то вроде
```
func main() {
	if err := run(); err != nil {
		panic("unexpected error: " + err.Error())
	}
}

```
далее там же отдельную функцию типа 
```
func run() error {
}

```
и уже  ее покрывать юнит-тестами.

2022-01-16 12:38 UTC, maffka123 commented
- инит у меня тоже вызвал вопросы, но так было в теор части...
- я попробовала переписать агент как ты предложил с тестами...что-то как-то сложно получается и вообще если их больше одного они не стартуют из-за переопределения флагов. Я хоть в том направлении думаю? а ctx и сигналы где определять в main или в run ?

2022-01-17 12:39 UTC, Bazys approved these changes

2022-01-17 16:33 UTC, merged